use crate::error::{HostError, Result};
use crate::proof::{Proof, RealProof};
use crate::receipt::Receipt;
use crate::security::SecurityLevel;
use prover_pipeline::{ProgramSource, ProofArtifact, ProofTarget};
use std::path::{Path, PathBuf};

mod cpu_prover;
mod dev_prover;
#[cfg(feature = "gpu-prover")]
mod gpu_prover;

pub use self::cpu_prover::{CpuProver, CpuProverBuilder};
pub use self::dev_prover::{DevProver, DevProverBuilder};
#[cfg(feature = "gpu-prover")]
pub use self::gpu_prover::{GpuProver, GpuProverBuilder, GpuProverConfig};

pub(super) const DEFAULT_RAM_BOUND_BYTES: usize = 1 << 30;
/// Upper bound on cycles the CPU prover is willing to replay for one proof.
pub(super) const DEFAULT_CPU_CYCLE_BOUND: usize = 1 << 31;

/// Host prover interface.
pub trait Prover {
    fn prove(&self, input_words: &[u32]) -> Result<ProveResult>;
}

/// Maximum proof layer generated by the prover.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default, serde::Serialize, serde::Deserialize)]
pub enum ProverLevel {
    Base,
    RecursionUnrolled,
    #[default]
    RecursionUnified,
}

impl ProverLevel {
    pub(crate) fn as_proof_target(self) -> ProofTarget {
        match self {
            ProverLevel::Base => ProofTarget::Base,
            ProverLevel::RecursionUnrolled => ProofTarget::RecursionUnrolled,
            ProverLevel::RecursionUnified => ProofTarget::RecursionUnified,
        }
    }

    pub(crate) fn from_proof_target(target: ProofTarget) -> Self {
        match target {
            ProofTarget::Base => ProverLevel::Base,
            ProofTarget::RecursionUnrolled => ProverLevel::RecursionUnrolled,
            ProofTarget::RecursionUnified => ProverLevel::RecursionUnified,
        }
    }
}

/// Proof and receipt produced by `prove`.
#[derive(Clone, Debug)]
pub struct ProveResult {
    pub proof: Proof,
    /// Cycles executed by the final proven layer. For [`ProverLevel::Base`]
    /// this is the program's own cycle count; for recursion levels it is the
    /// cycle count of the last recursion verifier run. Use a transpiler run
    /// (`Program::transpiler_runner`) when the program's cycle count is needed
    /// alongside a recursion proof.
    pub cycles: u64,
    pub receipt: Receipt,
}

pub(super) fn resolve_app_bin_path(path: &Path) -> Result<PathBuf> {
    let base_path = base_path(path)?;
    let app_bin_path = PathBuf::from(format!("{base_path}.bin"));

    if !app_bin_path.exists() {
        return Err(HostError::Prover(format!(
            "binary not found: {}",
            app_bin_path.display()
        )));
    }

    app_bin_path.canonicalize().map_err(|err| {
        HostError::Prover(format!(
            "failed to canonicalize binary path {}: {err}",
            app_bin_path.display()
        ))
    })
}

pub(super) fn resolve_text_path(app_bin_path: &Path) -> Result<PathBuf> {
    let mut app_text_path = app_bin_path.to_path_buf();
    app_text_path.set_extension("text");

    if !app_text_path.exists() {
        return Err(HostError::Prover(format!(
            "text file not found: {}",
            app_text_path.display()
        )));
    }

    app_text_path.canonicalize().map_err(|err| {
        HostError::Prover(format!(
            "failed to canonicalize text path {}: {err}",
            app_text_path.display()
        ))
    })
}

pub(super) fn base_path(app_bin_path: &Path) -> Result<String> {
    let path_str = app_bin_path
        .to_str()
        .ok_or_else(|| HostError::Prover("app path is not valid UTF-8".to_string()))?;
    if let Some(stripped) = path_str.strip_suffix(".bin") {
        Ok(stripped.to_string())
    } else {
        Ok(path_str.to_string())
    }
}

/// Resolve `app.bin` + the sibling `app.text` into a pipeline program source.
pub(super) fn program_source(app_bin_path: &Path) -> Result<ProgramSource> {
    let app_bin_path = resolve_app_bin_path(app_bin_path)?;
    let app_text_path = resolve_text_path(&app_bin_path)?;
    let to_string = |path: &Path| -> Result<String> {
        path.to_str()
            .map(str::to_string)
            .ok_or_else(|| HostError::Prover("app path is not valid UTF-8".to_string()))
    };
    Ok(ProgramSource::from_paths(
        to_string(&app_bin_path)?,
        Some(to_string(&app_text_path)?),
    ))
}

/// The pipeline only supports one compiled security level; reject anything else
/// up front so the mismatch is not discovered after a long proving run.
pub(super) fn ensure_supported_security(security: SecurityLevel) -> Result<()> {
    if security.to_pipeline() != prover_pipeline::COMPILED_SECURITY_LEVEL {
        return Err(HostError::Prover(format!(
            "security level {security} bits is not supported by the compiled prover ({:?})",
            prover_pipeline::COMPILED_SECURITY_LEVEL
        )));
    }
    Ok(())
}

pub(super) fn receipt_from_artifact(artifact: &ProofArtifact) -> Receipt {
    let mut registers = [0u32; 32];
    for (idx, reg) in artifact
        .proof
        .register_final_values
        .iter()
        .take(registers.len())
        .enumerate()
    {
        registers[idx] = reg.value;
    }
    Receipt::from_registers(registers)
}

pub(super) fn real_prove_result(
    artifact: ProofArtifact,
    security: SecurityLevel,
    level: ProverLevel,
) -> ProveResult {
    let receipt = receipt_from_artifact(&artifact);
    let cycles = artifact.cycles;
    let proof = Proof::Real(RealProof::new(security, level, artifact));
    ProveResult {
        proof,
        cycles,
        receipt,
    }
}
